---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-quarkus-app-5-dev
  namespace: janus-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: janus
  source:
    repoURL: https://github.com/slallemand/my-quarkus-app-5-gitops.git
    targetRevision: HEAD
    path: ./helm/app
    helm:
      parameters:
      - name: namespace.name
        value: my-quarkus-app-5-dev
      - name: environment
        value: dev
      - name: image.tag
        value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: my-quarkus-app-5-dev
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name|test(".-dockercfg-."))'
      kind: ServiceAccount
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
